Create database groupomania;

use groupomania;

CREATE TABLE users (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
lastName VARCHAR(50) NOT NULL,
firstName VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
createDate TIMESTAMP CURRENT_TIMESTAMP() NOT NULL,

avatar VARCHAR(200), 
description LONGTEXT,
updateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
lastRefreshDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE posts (
id INTEGER NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
userId INTEGER NOT NULL UNIQUE,
createDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

message LONGTEXT,
imageURL VARCHAR(200),
parentId. INTEGER,
updateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE likes (
userId INTEGER NOT NULL UNIQUE
postId INTEGER NOT NULL UNIQUE
like BOOLEAN,
likeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

show tables;

ALTER TABLE posts
ADD userId REFERENCES users(id)
ADD parentId REFERENCES posts(id)
ON DELETE CASCADE;

ALTER TABLE likes
ADD userId REFERENCES users(id)
ADD postsId REFERENCES posts(id)
ON DELETE CASCADE;