Create database groupomania;

use groupomania;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
   lastName VARCHAR(50) NOT NULL,
   firstName VARCHAR(50) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   password VARCHAR(100) NOT NULL,
    avatar VARCHAR(200),
    description LONGTEXT,
   createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   lastRefreshDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id INTEGER NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    userId INTEGER NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON 
    UPDATE CURRENT_TIMESTAMP,
    message LONGTEXT,
    imageURL VARCHAR(200),
    parentId INTEGER,
    updateAt TIMESTAMP
);

CREATE TABLE likes (
    userId INTEGER NOT NULL UNIQUE,		
    postId INTEGER NOT NULL UNIQUE,		
    likes BOOLEAN,
    likesDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

show tables;

ALTER TABLE posts
ADD FOREIGN KEY (userId) REFERENCES users (id)
ON DELETE CASCADE,
ADD FOREIGN KEY (parentId) REFERENCES posts (id)
ON DELETE CASCADE;

ALTER TABLE likes
ADD FOREIGN KEY (userId) REFERENCES users(id)
ON DELETE CASCADE,
ADD FOREIGN KEY (postId) REFERENCES posts(id)
ON DELETE CASCADE;